Repository CamiloGarciaLaRotta/watermelon-http-client, pull requests merged in 2020-04, with the labels that each got.

#8 fix: 'kind-of' dependency vulnerability
  package-lock.json
  package.json
Labels: security

#10 chore: add dependabot config file
  .dependabot/config.yml
Labels: dependencies, security

#25 Feat/headers
  .github/workflows/graphql_2.yml
  README.md
  __tests__/http.test.ts
  __tests__/integration.test.ts
  __tests__/main.test.ts
  action.yml
  dist/index.js
  src/http.ts
  src/main.ts
Labels: enhancement

#32 feat: add support for GraphQL variables for mutations
  .github/workflows/graphql_mutation.yml
  .github/workflows/graphql_query_1.yml
  .github/workflows/graphql_query_2.yml
  README.md
  __tests__/graphql.test.ts
  __tests__/integration.test.ts
  __tests__/main.test.ts
  action.yml
  dist/index.js
  src/graphql.ts
  src/main.ts
Labels: enhancement

#38 chore: remove non-dev dependencies from 'dependencies'
  jest.config.js
  package-lock.json
  package.json
Labels: dependencies

#41 feat: logger class
  .eslintrc.json
  README.md
  __tests__/http.test.ts
  __tests__/integration.test.ts
  __tests__/log.test.ts
  __tests__/main.test.ts
  action.yml
  dist/index.js
  package-lock.json
  package.json
  src/graphql.ts
  src/log.ts
  src/main.ts
Labels: enhancement

#44 feat: support 'operationName'
  README.md
  __tests__/graphql.test.ts
  action.yml
  dist/index.js
  src/graphql.ts
  src/main.ts
Labels: enhancement
